# Generated by Django 4.2.7 on 2023-11-24 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Posicion Jugador',
                'verbose_name_plural': 'Posicion Jugadores',
                'db_table': 'posicion_jugador',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_team', models.CharField(max_length=100, verbose_name='NombreEquipo')),
                ('flag_image', models.ImageField(blank=True, null=True, upload_to='media')),
                ('team_shield', models.ImageField(blank=True, null=True, upload_to='media')),
            ],
            options={
                'verbose_name': 'Equippo',
                'verbose_name_plural': 'Equipos',
                'db_table': 'equipo',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=50, verbose_name='Apellido')),
                ('player_photo', models.ImageField(blank=True, null=True, upload_to='media')),
                ('date_of_birth', models.DateField(verbose_name='Fecha Nacimiento')),
                ('position', models.CharField(max_length=50, verbose_name='Posicion')),
                ('jersey_number', models.PositiveIntegerField(verbose_name='Numero Camisa')),
                ('starter', models.CharField(choices=[('SI', 'Sí'), ('NO', 'No')], default='NO', max_length=2, verbose_name='Es Titular')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='core.team', verbose_name='Team')),
            ],
            options={
                'verbose_name': 'Jugador',
                'verbose_name_plural': 'Jugadores',
                'db_table': 'jugador',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=50, verbose_name='Apellido')),
                ('date_of_birth', models.DateField(verbose_name='FechaNacimiento')),
                ('nationality', models.CharField(choices=[('BRA', 'Brasil'), ('ARG', 'Argentina'), ('GER', 'Alemania'), ('ITA', 'Italia'), ('FRA', 'Francia'), ('ESP', 'España'), ('ENG', 'Inglaterra'), ('POR', 'Portugal'), ('NED', 'Países Bajos'), ('URU', 'Uruguay'), ('COL', 'Colombia')], max_length=3, verbose_name='Nacionalidad')),
                ('role', models.CharField(choices=[('tecnico', 'Tecnico'), ('asistente', 'Asistente'), ('medico', 'Medico'), ('preparador', 'Preparador')], max_length=20, verbose_name='Rol')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coaches', to='core.team', verbose_name='Team')),
            ],
            options={
                'verbose_name': 'Tecnico',
                'verbose_name_plural': 'Tecnicos',
                'db_table': 'tecnico',
                'ordering': ['id'],
            },
        ),
    ]
